<?
    $onSelected    = '';
    $offSelected   = '';
    $activateUrl   = "user/{$this->userProject->username}"
                     . '/projects/activate/id/'
                     . $this->userProject->id;
    $deactivateUrl = "user/{$this->userProject->username}"
                     . '/projects/deactivate/id/'
                     . $this->userProject->id;

    if ($this->userProject->isActive()) {
        $onLabel     = 'active';
        $offLabel    = 'archive';
        $onSelected  = 'selected';
    } else {
        $onLabel     = 'activate';
        $offLabel    = 'archived';
        $offSelected = 'selected';
    }
?>

<span class="action-link-toggle">
    <a class="action-link toggle-on <?= $onSelected ?>" href="<?= $this->baseUrl($activateUrl) ?>"><?= $onLabel ?></a>
    <a class="action-link toggle-off <?= $offSelected ?>" href="<?= $this->baseUrl($deactivateUrl) ?>"><?= $offLabel ?></a>
</span>