<div class="side-column-reorderable" data-reoder-url="user/<?= $this->username ?>/projects/reorder">
    <?
        $leftIcon = array(
            'src'   => $this->baseUrl('images/icons/reorder.png'),
            'title' => 'Reorder',
        );
        $rightIcon = array(
            'src'   => $this->baseUrl('images/icons/right-arrow.png'),
            'title' => 'Edit',
        );
        $params = array(
            'left-icon'  => $leftIcon,
            'right-icon' => $rightIcon,
        );
        foreach ($this->userProjectSet as $userProject) {
            $params['alt']      = !$userProject->isActive();
            $params['attr']     = array('data-id' => $userProject->id);
            $params['selected'] = ($this->selected == $userProject->id);
            $params['url']      = $this->baseUrl("user/{$userProject->username}/projects/edit/project_id/{$userProject->id}");

            echo $this->sideColumnItem($userProject->title, $params);
        }
    ?>
</div>

<?= $this->sideColumnItem('+ Add a New Project', array(
    'new'        => true,
    'right-icon' => $rightIcon,
    'selected'   => ('new' == $this->selected),
    'url'        => $this->baseUrl("user/{$this->username}/projects/new"),
));
?>