<?
foreach ($this->userProjectSet as $userProject) {
    $leftIcon = array(
        'src'   => $this->baseUrl('images/icons/reorder.png'),
        'title' => 'Reorder',
    );
    $rightIcon = array(
        'src'   => $this->baseUrl('images/icons/right-arrow.png'),
        'title' => 'Edit',
    );
    $params = array(
        'url'        => $this->baseUrl("user/{$userProject->username}/projects/edit/project_id/{$userProject->id}"),
        'selected'   => ($userProject->project_id == $this->selected),
        'left-icon'  => $leftIcon,
        'right-icon' => $rightIcon,
    );

    if (!$userProject->isActive()) {
        $params['alt'] = true;
    }

    echo $this->sideColumnItem($userProject->title, $params);
}
?>
<?= $this->button("+ Add a New Task", $this->baseUrl("{$userProject->username}/projects/new"), array('class' => 'new')) ?>