<h2>Edit details</h2>

<div class="action-links">
    <?= $this->partial('projects/_archive_toggler.phtml', array('userProject' => $this->userDataObj)) ?>
    <? if ($this->userDataObj->canDelete()) : ?>
    	<a class="action-link delete" href="<?= $this->baseUrl($this->deleteUrl) ?>">Delete?</a>
    <? endif ?>
    <?= $this->clear() ?>
</div>

<form action="" method="post">
    <?= $this->inlineEditing('title') ?>
    <?= $this->inlineEditing('subtitle') ?>
    <?= $this->inlineEditing('description') ?>
</form>