<?
    $deleteUrl = 'user/' . $this->username
                 . '/projects/delete/project_id/'
                 . $this->userProject->project_id;

    $this->inlineEditing()->setForm($this->form)
                          ->setDataObject($this->userProject);
?>
<?= $this->partial('projects/list.phtml', array(
    'selected'       => $this->userProject->project_id,
    'username'       => $this->username,
    'userProjectSet' => $this->userProjectSet,
)) ?>
<section id="settings-main-content" class="layout-column-fluid">
    <div class="section">
        <h2>Edit details</h2>

        <div class="inline-row-editing" id="project-archive-toggler-wrapper">
            <?= $this->partial('projects/_archive_toggler.phtml', array('userProject' => $this->userProject)) ?>
            <a id="inline-row-editing-delete" href="<?= $this->baseUrl($deleteUrl) ?>">Delete?</a>
            <?= $this->clear() ?>                
        </div>

        <form action="" method="post">
            <?= $this->inlineEditing('title') ?>
            <?= $this->inlineEditing('subtitle') ?>
            <?= $this->inlineEditing('description') ?>
        </form>
    </div>
</section>