<section id="projects">
    <? if (count($this->userProjectSet) > 0) : ?>
        <a title="Manage your projects" class="floating-label" href="<?= $this->baseUrl("user/{$this->username}/projects/list") ?>">Projects »</a>
        <?
            $params = array();
            foreach ($this->userProjectSet as $userProject) {
                $params['alt']      = !$userProject->isActive();
                $params['attr']     = array('data-id' => $userProject->getId());
                $params['class']    = 'project row';
                $params['subtitle'] = $userProject->subtitle;
                $params['url']      = $this->baseUrl("user/{$this->username}/projects/edit/id/{$userProject->id}");

                echo $this->sideColumnItem($userProject->getName(), $params);
            }
        ?>
    <? endif ?>
</section>