<?
$totalUserProjects = count($this->userProjectSet);
$newProjectUrl     = $this->baseUrl("user/{$this->user->username}/projects/new");

// return to timesheet after adding a project
$newProjectUrl .= '?next_url=' . "user/{$this->user->username}/timesheets/manage/date/{$this->dateObj->toString('YYYY-MM-dd')}";
?>
<section id="timesheet">
    <div class="side-column-with-border layout-fuild-left-column">
        <? if ($totalUserProjects > 0) : ?>
            <?= $this->partial('timesheets/_date.phtml', array('dateObj' => $this->dateObj)) ?>
        <? endif ?>

        <?= $this->partial('timesheets/_projects.phtml', array('userProjectSet' => $this->userProjectSet, 'username' => $this->user->username)) ?>

        <div class="side-column" id="project-actions">
            <?= $this->button('+ Add a new project', $newProjectUrl, array('class' => 'new')) ?>
        </div>
    </div>

    <? if ($totalUserProjects > 0) : ?>
        <div class="layout-fluid-right-column">
            <?= $this->partial('timesheets/_hours_header.phtml', array('dateObj' => $this->dateObj)) ?>
            <?= $this->partial('timesheets/_jobs.phtml', array('userProjectSet' => $this->userProjectSet)) ?>
        </div>
    <? endif ?>

    <?= $this->partial('timesheets/_tasks.phtml', array('userTaskSet' => $this->userTaskSet, 'username' => $this->user->username)) ?>

</section>

<? $this->inlineScript()->captureStart() ?>
$(function() {
    window.timesheets = Chronflux.Timesheets({
        user: {
            id         : <?= Zend_Json::encode($this->user->id) ?>,
            username   : <?= Zend_Json::encode($this->user->username) ?>,
            clock_in_at: <?= Zend_Json::encode($this->user->clock_in_at) ?>,
        }
    });
});
<? $this->inlineScript()->captureEnd() ?>