<?
$newProjectUrl = $this->baseUrl("user/{$this->user->username}/projects/new");
?>
<section id="timesheet">
    <div class="side-column-with-border layout-fuild-left-column">
        <?= $this->partial('timesheets/_date.phtml', array('dateObj' => $this->dateObj)) ?>
        <?= $this->partial('timesheets/_projects.phtml', array('userProjectSet' => $this->userProjectSet, 'username' => $this->user->username)) ?>

        <div class="side-column" id="project-actions">
            <?= $this->button('+ Add a new project', $newProjectUrl, array('class' => 'new')) ?>
        </div>
    </div>

    <? if (count($this->userProjectSet) > 0) : ?>
        <div class="layout-fluid-right-column">
            <?= $this->partial('timesheets/_hours_header.phtml', array('dateObj' => $this->dateObj)) ?>
            <?= $this->partial('timesheets/_jobs.phtml', array('userProjectSet' => $this->userProjectSet)) ?>
        </div>
    <? endif ?>

    <?= $this->partial('timesheets/_tasks.phtml', array('userTaskSet' => $this->userTaskSet, 'username' => $this->user->username)) ?>

</section>

<? $this->inlineScript()->captureStart() ?>
$(function() {
    Chronflux.Timesheets({
        user: {
            username: <?= Zend_Json::encode($this->user->username) ?>,
            id      : <?= Zend_Json::encode($this->user->id) ?>
        }
    });
});
<? $this->inlineScript()->captureEnd() ?>