<?
    // store view reference to pass to value renderer
    $view = $this;
?>
<h2>Edit details</h2>

<? if ($this->userDataObj->canDelete()) : ?>
<div class="action-links">
    <a class="action-link delete" href="<?= $this->baseUrl($this->deleteUrl) ?>">Delete?</a>
    <?= $this->clear() ?>
</div>
<? endif ?>

<div id="task-form-wrapper">
    <form action="" method="post">
        <?= $this->inlineEditing('name') ?>
        <?= $this->inlineEditing('abbreviation') ?>
        <?= $this->inlineEditing('color', array('value_renderer' => function($value) use($view) {
            return $view->bubble(array('color' => $value));
        })) ?>
        <?= $this->inlineEditing('description') ?>
    </form>
</div>