<?
$menuItems = array(
    'Timesheets' => $this->baseUrl("user/{$this->username}/timesheets/manage"),
    'Reports'    => '#',
    'Settings'   => $this->baseUrl("user/{$this->username}/settings"),
);
?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
        <?= $this->headStyle() ?>
    </head>
    <body>
        <header id="main-header">
            <nav id="main-menu">
                <ul class="inline-buttons">
                    <? foreach ($menuItems as $label => $url) : ?>
                        <? $selected = ($this->selectedMenuItem == strtolower($label)) ?>
                        <li <?= ($selected) ? 'class="selected"' : '' ?>>
                            <a href="<?= $url ?>" class="button <?= ($selected) ? 'selected' : '' ?>">
                                <span class="icon">
                                    <img class="loader" src="<?= $this->baseUrl('images/icons/loader.gif') ?>" title="Loader" />
                                </span>
                                <label><?= $label ?></label>
                            </a>
                            <span class="arrow"></span>
                        </li>
                    <? endforeach ?>
                </ul>
            </nav>

            <section id="header-user-auth">
                <ul class="inline-buttons">
                   <li>
                       <a href="#" class="button">
                           <div class="icon">
                               <img class="thumb" src="" />
                           </div>
                           <label>gmathieu</label>
                       </a>
                   </li>
                   <li>
                       <a href="#" id="logout" title="Log out" class="button">
                           <label>X</label>
                       </a>
                   </li>
                </ul>
            </section>

           <?= $this->clear() ?>
        </header>

        <?= $this->layout()->content; ?>
    </body>
    <?= $this->inlineScript() ?>
</html>